#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

PROG="/usr/local/sbin/restore-dnsproxy-after-sysupgrade"

start_service() {
	[ -x "$PROG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param term_timeout 10
	procd_close_instance
}
