#!/bin/sh

case "${ACTION:-}" in
	ifup|ifupdate)
		;;
	*)
		exit 0
		;;
esac

case "${INTERFACE:-}" in
	wan|wan6)
		;;
	*)
		exit 0
		;;
esac

PROG="/usr/local/sbin/restore-dnsproxy-after-sysupgrade"
[ -x "$PROG" ] || exit 0

"$PROG" --check >/dev/null 2>&1 && exit 0

( "$PROG" </dev/null >/dev/null 2>&1 ) &
